# Generated by Django 4.1.3 on 2022-11-08 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="url",
            field=models.SlugField(max_length=130, unique=True),
        ),
        migrations.AlterField(
            model_name="movie",
            name="actors",
            field=models.ManyToManyField(
                related_name="film_actor", to="movies.actor", verbose_name="Актёр"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="genres",
            field=models.ManyToManyField(to="movies.genre", verbose_name="Жанр"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="url",
            field=models.SlugField(max_length=130, unique=True),
        ),
        migrations.AlterField(
            model_name="ratingstar",
            name="value",
            field=models.SmallIntegerField(default=0, verbose_name="Значение"),
        ),
    ]
